config/routes.rb
Rails.application.routes.draw do
  get '/games/cheapest', to: 'games#cheapest'

  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  resources :games, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update] do
    resources :games, only: [:index, :new]
  end
  resources :plays, only: [:show]
  root 'sessions#new'



  get '/auth/facebook/callback', to: 'sessions#create'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  post '/play', to: 'plays#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :plays
  has_many :users, through: :plays
  belongs_to :manufacturer

  validates :name, presence: true, uniqueness: true
  validates :token_cost, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  accepts_nested_attributes_for :manufacturer, reject_if: :all_blank

  scope :playable, ->(tokens) { where("token_cost <= ?", tokens).order(name: :asc)}
  scope :cheapest, ->() { order(token_cost: :asc).limit(3) }
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validate :playable?, on: :create

  def play_game
    self.user.tokens -= self.game.token_cost
    self.user.save(validate: false)
  end

  def playable?
    errors.add(:tokens, "Insufficient tokens") if self.user.tokens < self.game.token_cost
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :games, through: :plays
  has_secure_password

  validates :name, uniqueness: true, length: { in: 2..20}
  validates :password, presence: true, on: :create


  def played_games
    self.games.order(name: :asc).uniq
  end

  def show_plays
    self.plays.order(id: :desc)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :is_logged_in?, :require_logged_in, :require_admin, :clear_edit_id

  def current_user
    if is_logged_in?
      User.find_by_id(session[:user_id])
    end
  end

  def is_logged_in?
    session[:user_id].present?
  end

  def require_logged_in
    redirect_to root_url unless is_logged_in?
  end

  def require_admin
    redirect_to games_path, notice: "You don't have permission to do that" unless current_user.admin
  end

  def clear_edit_id
    session.delete :edit_id
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit, :update]
  before_action :require_logged_in
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    params[:manufacturer_id].nil? ? @games = Game.all : @games = Manufacturer.find_by(id: params[:manufacturer_id]).games

    # @all_games = Game.all.order(name: :asc)
    # @playable_game = Game.playable(current_user.tokens)
  end


  def cheapest
    @games = Game.cheapest
  end

  def show
  end


  def new
    @game = Game.new(manufacturer_id: params[:manufacturer_id])
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  def edit
    session[:edit_id] = params[:id]
  end

  def update
    if session[:edit_id] != params[:id]
      clear_edit_id
      return redirect_to game_path(session[:edit_id]), notice: "You can't do that"
    end

    @game.update(game_params)
    if @game.valid?
      clear_edit_id
      redirect_to game_path(@game)
    else
      render :edit
    end
  end

  def destroy
    Game.destroy(params[:id])
    Play.where(game_id: params[:id]).destroy_all
    redirect_to games_path
  end

  private

  def find_game
    @game = Game.find_by(id: params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :token_cost, :manufacturer_id, manufacturer_attributes: [:name])
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :find_manufacturer, only: [:show, :edit, :update]
  before_action :require_logged_in
  before_action :require_admin, only: [:new, :create, :edit, :update]

  def index
    @manufacturers = Manufacturer.all
  end

  def show
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.create(manufacturer_params)
    if @manufacturer.valid?
      redirect_to manufacturer_path(@manufacturer)
    else
      render :new
    end
  end

  def edit
    session[:edit_id] = params[:id]
  end

  def update
    if session[:edit_id] != params[:id]
      clear_edit_id
      return redirect_to manufacturer_path(session[:edit_id]), notice: "You can't do that"
    end



    @manufacturer.update(manufacturer_params)
    if @manufacturer.valid?
      clear_edit_id
      redirect_to manufacturer_path(@manufacturer)
    else
      render :edit
    end
  end

  private

  def find_manufacturer
    @manufacturer = Manufacturer.find_by(id: params[:id])
  end

  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :require_logged_in

  def show
    @play = Play.find_by(id: params[:id])
  end

  def create
    play = Play.create(plays_params)
    if play.valid?
      play.play_game
      redirect_to play_path(play)
    else
      return redirect_to game_path(play.game), notice: "Insufficient tokens"
    end
  end

  private

  def plays_params
    params.require(:plays).permit(:game_id, :difficulty, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]

  def new
    redirect_to games_path if is_logged_in?
  end

  def create
    if auth.present?
      @user = User.find_or_initialize_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
      end
      @user.save(validate: false) if @user.new_record?
    else
      @user = User.find_by(name: params[:name])
      return redirect_to root_url,
                         notice: 'Username or password incorrect' if @user.nil? || !@user.authenticate(params[:password])
    end

    session[:user_id] = @user.id
    redirect_to games_path
  end

  def destroy
    session.delete :user_id
    redirect_to root_url
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]
  before_action :require_logged_in, except: [:new, :create]
  helper_method :facebook_user?

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params(:name, :password))
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to games_path
    else
      render :new
    end
  end

  def edit
    return redirect_to user_path(params[:id]), notice: "You don't have permission to do that" unless params[:id].to_i == session[:user_id]
    return redirect_to user_path(params[:id]), notice: "You cannot edit your facebook login" if facebook_user?
    session[:edit_id] = params[:id]
  end

  def update
    if session[:edit_id] != params[:id]
      clear_edit_id
      redirect_to user_path(session[:edit_id]), notice: "You can't do that"
    end

    @user.update(user_params(:name))
    if @user.valid?
      clear_edit_id
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params(*args)
    params.require(:user).permit(*args)
  end

  def facebook_user?
    return current_user.uid.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/cheapest.html.erb
<% @games.each do |game| %>
  <%= link_to game.name, game_path(game) %>
  <br>
<% end %>

app/views/games/edit.html.erb
<%= render partial: "layouts/errors", locals: { issue: @game } %>

<div class="row">
  <div class="col offset-md-4 col-md-4">
    <%= form_for @game do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :token_cost %>
        <%= f.number_field :token_cost, class: "form-control" %>
      </div>
      <br>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/games/index.html.erb
<div class="row">
  <% if current_user.admin %>
    <%= button_to "Create Game", new_game_path(@game), method: 'get', class: "btn btn-primary"%>
  <% end %>
</div>
<br>
<div class="row">
  <div class="col col-md-6">
    <h3>All Games</h3>
    <% @games.order(name: :asc).each do |game| %>
      <div class="col">
        <%= link_to game.name, game_path(game) %>
      </div>
    <% end %>
  </div>
  <div class="col col-md-6">
    <h3>Playable Games</h3>
    <% @games.playable(current_user.tokens).each do |game| %>
    <%# @playable_games.each do |game| %>
      <div class="col">
        <%= link_to game.name, game_path(game) %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<%= render partial: "layouts/errors", locals: { issue: @game } %>

<div class="row">
  <div class="col offset-md-4 col-md-4">
    <%= form_for @game do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :token_cost %>
        <%= f.number_field :token_cost, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :manufacturer %>
        <%= collection_select :game, :manufacturer_id, Manufacturer.all, :id, :name, include_blank: 'Choose a Manufacturer' %>
      </div>

      <h4>Or create a new manufacturer</h4>
      <%= f.fields_for :manufacturer, @game.build_manufacturer do |m_fields| %>
        <div class="form-group">
          <%= m_fields.label :manufacturer_name %>
          <%= m_fields.text_field :name, class: "form-control" %>
        </div>
      <% end %>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="row">
  <h2 class="col col-md-10"><%= @game.name %></h2>
  <% if current_user.admin %>
    <%= button_to "Edit", edit_game_path(@game), method: 'get', class: "btn btn-primary"%>
    <%= button_to "Delete", game_path(@game), method: 'delete', class: "btn btn-danger"%>
  <% end %>
</div>

<div class="row">
  <h4 class="col"><%= @game.token_cost %> tokens.</h4>
</div>

<div class="row">
  <%= form_tag "/play", method: "post" do %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag 'plays[game_id]', @game.id %>
    <%= hidden_field_tag 'plays[user_id]', session[:user_id] %>
    <div class="form_group">
      <%= select_tag 'plays[difficulty]', options_for_select(%w[Easy Medium Hard]) %>
    </div>
    <br>
    <%= button_tag "Play", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if issue.errors.any? %>
  <div id="error_explanation">
    <% issue.errors.full_messages.each do |msg| %>
      <div style="color: red;" data-alert class="col text-center alert-box radius">
        <%= msg %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsArcade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% if is_logged_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
          <div class="navbar-nav mr-auto">
            <%= link_to "Games", games_path, class: "nav-item nav-link" %>
            <%= link_to "Users", users_path, class: "nav-item nav-link" %>
            <%= link_to "Manufacturers", manufacturers_path, class: "nav-item nav-link" %>
          </div>
          <div class="navbar-nav">
            <%= link_to "(#{current_user.tokens}) Profile", user_path(session[:user_id]), class: "nav-item nav-link" %>
            <%= link_to "Log Out", signout_path, method: :delete, class: "nav-item nav-link" %>
          </div>
        </div>
      </nav>
    <% end %>

    <% flash.keys.each do |type| %>
      <div style="color: red;" data-alert class="col text-center flash <%= type %> alert-box radius">
        <%= flash[type] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/manufacturers/_form.html.erb
<div class="row">
  <div class="col offset-md-4 col-md-4">
    <%= form_for @manufacturer do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/manufacturers/edit.html.erb
<%= render partial: "layouts/errors", locals: { issue: @manufacturer } %>

<%= render partial: "form" %>

app/views/manufacturers/index.html.erb
<div class="row">
  <% if current_user.admin %>
    <%= button_to "Create Manufacturer", new_manufacturer_path(@manufacturer), method: 'get', class: "btn btn-primary"%>
  <% end %>
</div>
<br>
<div class="row">
  <% @manufacturers.each do |manufacturer| %>
    <div class="col col-md-3">
      <%= link_to manufacturer.name, manufacturer_path(manufacturer) %>
    </div>
  <% end %>
</div>

app/views/manufacturers/new.html.erb
<%= render partial: "layouts/errors", locals: { issue: @manufacturer } %>

<%= render partial: "form" %>

app/views/manufacturers/show.html.erb
<div class="row">
  <h2 class="col col-md-10"><%= @manufacturer.name %></h2>
  <% if current_user.admin %>
    <%= button_to "Edit", edit_manufacturer_path(@manufacturer), method: 'get', class: "btn btn-primary"%>
  <% end %>
</div>

<% if current_user.admin %>
  <div class="row">
    <%= link_to "Create Game", new_manufacturer_game_path(@manufacturer) %>
  </div>
<% end %>

<div class="row">
  <%= link_to "Show Games", manufacturer_games_path(@manufacturer) %>
</div>

app/views/plays/show.html.erb
<div class="row">
  <h2>Now playing <%= @play.game.name %></h2>
</div>

<div class="row">
  <h3>Difficulty: <%= @play.difficulty %></h3>
</div>
<div class="row">
  <h3>Have fun!</h3>
</div>

<div class="row">
  <p class="col"><%= link_to "Play again!", game_path(@play.game) %></p>
  <p class="col"><%= link_to "Back to browse", games_path %></p>
</div>

app/views/users/edit.html.erb
<%= render partial: "layouts/errors", locals: { issue: @user } %>

<div class="row">
  <div class="col offset-md-4 col-md-4">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col col-md-3">
      <h3><%= link_to user.name, user_path(user) %></h3>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render partial: "layouts/errors", locals: { issue: @user } %>

<div class="row">
  <div class="col offset-md-4 col-md-4">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
    <p>or <%= link_to "sign in", root_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col col-md-10">
    <h3>Name: <%= @user.name %></h3>
  </div>
  <% if @user.id == session[:user_id] && !facebook_user? %>
    <%= button_to "Edit", edit_user_path(@user), method: 'get', class: "btn btn-primary"%>
  <% end %>
</div>

<div class="row">
  <div class="col col-md-4">
    <h4>Tokens: <%= @user.tokens %></h4>
  </div>
</div>

<div class="row">
  <div class="col col-md-6">
    <h3>Games</h3>
    <% @user.played_games.each do |game| %>
      <div class="row">
        <p><%= link_to game.name, game_path(game) %></p>
      </div>
    <% end %>
  </div>

  <div class="col col-md-6">
    <h3>Plays</h3>
    <% @user.show_plays.each do |play| %>
      <div class="row">
        <p><%= "#{play.game.name} on #{play.difficulty}" %></p>
      </div>
    <% end %>
  </div>
</div>